### ISSUE TITLE
圈選的連結能否不要在新分頁自動開啟

### ISSUE THREAD

**Issue by bingthian** [eight04/linky-square#1]
已圈選的連結，會在放開滑鼠左鍵時在新分頁自動開啟
如果一次選取太多，連續開一大串分頁很嚇人，要關閉也費力
比較傾向圈選後即自動獲取連結
這樣可以避免沒按到c或按錯鍵時，遇到前述問題

**Comment by eight04** [comment]
已於 0.2.0 修正
