### ISSUE TITLE
無法在 file:// 路徑底下的 .htm 執行

### ISSUE THREAD

**Issue by bingthian** [eight04/linky-square#2]
已在 about:config 裡將 greasemonkey.fileIsGreaseable 值改為 true

**Comment by eight04** [comment]
因為這個腳本預設只在 http* 底下運作︰
https://github.com/eight04/linky-square/blob/master/dist/linky.user.js#L7

感覺應該改成 *

**Comment by eight04** [comment]
已於 0.2.0 修正
