### ISSUE TITLE
Links behind images should be styled

### ISSUE THREAD

**Issue by Keith94** [eight04/linky-square#3]
When selecting a link behind an `img` element, it should change the image background color/border or something to show it's been selected. For comparison:

Linky Square:
![image](https://cloud.githubusercontent.com/assets/5490615/22483807/a6519b2a-e7b3-11e6-94b3-38ec0f25f8c2.png)

Snap Links:
![firefox_2017-01-31_12-44-49](https://cloud.githubusercontent.com/assets/5490615/22483781/8bcbdd4c-e7b3-11e6-8692-cfd2819425d2.png)

**Comment by eight04** [comment]
Fixed in 0.2.1
